name-template: 'taosgen v$NEXT_PATCH_VERSION Release'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ## This release includes:

  $CHANGES

  ## Download

  - [taosgen-${{ nextRelease.version }}-linux-x64.tar.gz](https://github.com/taosdata/taosgen/releases/download/v${{ nextRelease.version }}/taosgen-v${{ nextRelease.version }}-linux-x64.tar.gz)
  - [taosgen-${{ nextRelease.version }}-linux-arm64.tar.gz](https://github.com/taosdata/taosgen/releases/download/v${{ nextRelease.version }}/taosgen-v${{ nextRelease.version }}-linux-arm64.tar.gz)
  - [taosgen-${{ nextRelease.version }}-macos-x64.tar.gz](https://github.com/taosdata/taosgen/releases/download/v${{ nextRelease.version }}/taosgen-v${{ nextRelease.version }}-macos-x64.tar.gz)
  - [taosgen-${{ nextRelease.version }}-macos-arm64.tar.gz](https://github.com/taosdata/taosgen/releases/download/v${{ nextRelease.version }}/taosgen-v${{ nextRelease.version }}-macos-arm64.tar.gz)