name-template: 'taosgen v$NEXT_PATCH_VERSION Release'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  ### This release includes:

  {% for category in categories %}
  {% if category.changes %}
  #### {{ category.title }}
  {{ category.changes }}
  {% endif %}
  {% endfor %}

  ## Download

  - [taosgen-v$NEXT_PATCH_VERSION-linux-x64.tar.gz](https://github.com/taosdata/taosgen/releases/download/v$NEXT_PATCH_VERSION/taosgen-v$NEXT_PATCH_VERSION-linux-x64.tar.gz)
  - [taosgen-v$NEXT_PATCH_VERSION-linux-arm64.tar.gz](https://github.com/taosdata/taosgen/releases/download/v$NEXT_PATCH_VERSION/taosgen-v$NEXT_PATCH_VERSION-linux-arm64.tar.gz)
  - [taosgen-v$NEXT_PATCH_VERSION-macos-x64.tar.gz](https://github.com/taosdata/taosgen/releases/download/v$NEXT_PATCH_VERSION/taosgen-v$NEXT_PATCH_VERSION-macos-x64.tar.gz)
  - [taosgen-v$NEXT_PATCH_VERSION-macos-arm64.tar.gz](https://github.com/taosdata/taosgen/releases/download/v$NEXT_PATCH_VERSION/taosgen-v$NEXT_PATCH_VERSION-macos-arm64.tar.gz)