tdengine:
  dsn: taos+ws://root:taosdata@127.0.0.1:6041/tsbench
  drop_if_exists: true
  props: precision 'us' vgroups 4

schema:
  name: meters
  from_csv:
    tags:
      file_path: ../conf/ctb-tags.csv
      tbname_index: 2
      exclude_indices:
    columns:
      file_path: ../conf/ctb-data.csv
      tbname_index : 0
      timestamp_index: 1
      timestamp_precision: ms
      timestamp_offset:
        offset_type: relative
        value: +10s
      repeat_read: false
  columns:
    - name: ts
      type: timestamp
      start: now
      precision : us
      step: 1
    - name: current
      type: float
    - name: voltage
      type: int
    - name: phase
      type: float
  tags:
    - name: groupid
      type: int
    - name: location
      type: binary(24)
  generation:
    interlace: 1
    per_table_rows: 100
    per_batch_rows: 10000

jobs:
  # TDengine insert job
  insert-data:
    needs: []
    steps:
      - uses: tdengine/create-super-table
      - uses: tdengine/create-child-table
        with:
          batch:
            size: 1000
            concurrency: 10
      - uses: tdengine/insert-data
        with:
          concurrency: 8