tdengine:
  dsn: taos+ws://root:taosdata@127.0.0.1:6041/tsbench
  drop_if_exists: true
  props: precision 'ms' vgroups 4

schema:
  name: meters
  tbname: &tbname
    prefix: d
    count: 10000
    from: 0
  columns: &columns
    - name: ts
      type: timestamp
      start: now
      precision : ms
      step: 1
    - name: current
      type: float
      min: 0
      max: 100
    - name: voltage
      type: int
      min: 200
      max: 240
    - name: phase
      type: float
      expr: _i * math.pi % 180
  tags: &tags
    - name: groupid
      type: int
      min: 1
      max: 10
    - name: location
      type: binary(24)
      values:
        - New York
        - Los Angeles
        - Chicago
        - Houston
        - Phoenix
        - Philadelphia
        - San Antonio
        - San Diego
        - Dallas
        - Austin
  generation: &generation
    interlace: 1
    per_table_rows: 100
    per_batch_rows: 10000

ev_schema: &ev_schema
  name: ev
  tbname:
    prefix: ev
    count: 50000
    from: 1
  columns:
    - name: ts
      type: timestamp
      start: now
      precision: ms
      step: 60
    - name: charge_power
      type: float
      min: 0
      max: 350
    - name: battery_level
      type: int
      min: 0
      max: 100
    - name: session_duration
      type: int
      min: 1
      max: 1440
    - name: temperature
      type: float
      min: -20
      max: 60
  tags:
    - name: station_id
      type: binary(16)
      values:
        - ST001
        - ST002
        - ST003
        - ST004
        - ST005
    - name: vehicle_type
      type: binary(24)
      values:
        - Sedan
        - SUV
        - Truck
        - Bus
        - Van
    - name: city
      type: binary(24)
      values:
        - Shanghai
        - Beijing
        - Shenzhen
        - Hangzhou
        - Chengdu
  generation:
    interlace: 2
    per_table_rows: 500
    per_batch_rows: 5000

concurrency: 2
jobs:

  # TDengine create database job
  create-db:
    steps:
      - uses: tdengine/create-database


  # TDengine insert meters job
  insert-data-meters:
    needs: [create-db]
    steps:
      - uses: tdengine/create-super-table
      - uses: tdengine/create-child-table
        with:
          batch:
            size: 1000
            concurrency: 10

      - uses: tdengine/insert-data
        with:
          concurrency: 8

  # TDengine insert ev job
  insert-data-ev:
    needs: [create-db]
    steps:
      - uses: tdengine/create-super-table
        with:
          schema: *ev_schema

      - uses: tdengine/create-child-table
        with:
          batch:
            size: 1000
            concurrency: 10

      - uses: tdengine/insert-data
        with:
          concurrency: 8
